-----------------------------------------------------------------------------------------------------------
-- Author:		Parker Smart
-- Date:		12/22/2005
-- Description:	The following code GENERATES SQL code print out record counts of filtered tables.
--

SET NOCOUNT ON

DECLARE @mm_dd_yyyy			INT
DECLARE @HH_MM_SS_mmm		INT
SET 	@mm_dd_yyyy		= 101
SET 	@HH_MM_SS_mmm	= 14


DECLARE @newLine	AS CHAR(1)
SET		@newLine = '
'

PRINT '----------------------------------------------------------------------------'
PRINT '-- DATE:         ' + CONVERT(VARCHAR(13), getdate(), @mm_dd_yyyy) + ' ' + CONVERT(VARCHAR(13), getdate(), @HH_MM_SS_mmm)
PRINT '-- USER:         ' + user_name()
PRINT '--'
PRINT '-- This file generated by "View Tables - Generate Counts.sql" Created by P.Smart'
PRINT '--'
PRINT ''

PRINT 'SET NOCOUNT ON'
PRINT ''

PRINT 'PRINT ''__Table_Name_______________________________Count___'''

select 'DECLARE	@count_' + cast(name as char(32)) + ' AS INT' + @newLine
from sysobjects so
where	xtype = 'U'
and		name not in ('dtproperties')
AND (so.[name]			LIKE 'act__t%'
OR		so.[name]		LIKE 'bat__t%'
OR		so.[name]		LIKE 'col__t%'
OR		so.[name]		LIKE 'fil__t%'
OR		so.[name]		LIKE 'nte__t%'
OR		so.[name]		LIKE 'prt__t%'
OR		so.[name]		LIKE 'utl__t%'
--OR		so.[name]		LIKE 'wrk71t_chela_key_%'
)
order by name

select 'SET @count_' + cast(name as char(32)) + ' = (SELECT COUNT(*) FROM ' + cast(name as char(32)) + ' (NOLOCK))' + @newLine
from	sysobjects so
where	xtype = 'U'
and		name not in ('dtproperties')
AND (so.[name]			LIKE 'act__t%'
OR		so.[name]		LIKE 'bat__t%'
OR		so.[name]		LIKE 'col__t%'
OR		so.[name]		LIKE 'fil__t%'
OR		so.[name]		LIKE 'nte__t%'
OR		so.[name]		LIKE 'prt__t%'
OR		so.[name]		LIKE 'utl__t%'
--OR		so.[name]		LIKE 'wrk71t_chela_key_%'
)
order by name

select 'PRINT ''' + cast(name as char(32)) + ' = '' '
		+	'+ SPACE(16 - LEN(CONVERT(VARCHAR(16), CONVERT(MONEY, @count_' + cast(name as varchar(50)) + '), 1)))' + @newLine
		+	'								'
		+	'+ LEFT(CONVERT(VARCHAR(16), CONVERT(MONEY, @count_' + cast(name as varchar(50)) + '), 1), LEN(CONVERT(VARCHAR(16), CONVERT(MONEY, @count_' + cast(name as varchar(50)) + '), 1)) - 3)' + @newLine --+ @newLine
--		+ 'GO' + @newLine
from sysobjects so
where	xtype = 'U'
and		name not in ('dtproperties')
AND (so.[name]			LIKE 'act__t%'
OR		so.[name]		LIKE 'bat__t%'
OR		so.[name]		LIKE 'col__t%'
OR		so.[name]		LIKE 'fil__t%'
OR		so.[name]		LIKE 'nte__t%'
OR		so.[name]		LIKE 'prt__t%'
OR		so.[name]		LIKE 'utl__t%'
--OR		so.[name]		LIKE 'wrk71t_chela_key_%'
)
order by name

PRINT 'DECLARE	@count_ALL AS INT'
PRINT 'SET		@count_ALL = 0'

select 'SET @count_ALL = @count_ALL + @count_' + cast(name as varchar(50))
from sysobjects so
where	xtype = 'U'
and		name not in ('dtproperties')
AND (so.[name]			LIKE 'act__t%'
OR		so.[name]		LIKE 'bat__t%'
OR		so.[name]		LIKE 'col__t%'
OR		so.[name]		LIKE 'fil__t%'
OR		so.[name]		LIKE 'nte__t%'
OR		so.[name]		LIKE 'prt__t%'
OR		so.[name]		LIKE 'utl__t%'
--OR		so.[name]		LIKE 'wrk71t_chela_key_%'
)
order by name

PRINT 'PRINT CAST(''Totals'' AS CHAR(32)) + '' = '' + SPACE(16 - LEN(CONVERT(VARCHAR(16), CONVERT(MONEY, @count_ALL), 1))) ' + @newLine +
		'											+ LEFT(CONVERT(VARCHAR(16), CONVERT(MONEY, @count_ALL), 1), LEN(CONVERT(VARCHAR(16), CONVERT(MONEY, @count_ALL), 1)) - 3)'
